### ISSUE TITLE
Office 2021 on Windows XP SP1 x86

### ISSUE THREAD

**Issue by ALLMAC123** [Skulltrail192/One-Core-API-Binaries#161]
How do I run Office 2021 on Windows XP SP1 x86?

**Comment by FoxbitDreamtail** [comment]
> How do I run Office 2021 on Windows XP SP1 x86?

idealy, you wouldn't use ms office at all, use lebre office or open office, anyway, to get this working you NEED to be running SP3 of Windows XP, I recommend [Legacy update](https://legacyupdate.net/) for this, then install the onecore api package, then try Lebre Office but I would not try MS Office 2021.

IF SP3 BREAKS DRIVERS GO BACK TO 2K SP4! you can modernize 2k to suit your needs, plus it will be faster than xp due to it being older.
A simple google search will do you good.

**Comment by bw134polska** [comment]
Unlikely - Windows XP SP1 is out of date and you can't install even Office 2007 on it. Better try with SP3 but the attempts would be unsuccessful.

**Comment by Skulltrail192** [comment]
Windows XP SP1 is not supported and for now we cannot install Office 2013+ on XP/2003. This issue will be closed.
