### ISSUE TITLE
Supermium 122 crashes upon launch with One-Core-API

### ISSUE THREAD

**Issue by mina354** [Skulltrail192/One-Core-API-Binaries#268]
When One-Core-API is installed, Supermium 122 crashes upon launch. However, without One-Core-API, it runs normally.
I used One-Core-API-Canary 4.0.0-20240210-experimental.
VMware Workstation 17.5.0 with a Windows XP Professional Service Pack 3 (no updates) VM with only Supermium installed, no other programs.
If you need more information, I'd be more than happy to supply you with them.

**Comment by jonm58** [comment]
https://github.com/Skulltrail192/One-Core-API-Binaries/issues/178
"Supermium 121 crashes on startup, with debug.log showing that it failed to load chrome.dll. This is due to progwrp TLS code conflicting with already existing TLS implementations. This also happens under WinXP compatibility mode on Win7

Workaround: Spoof your OS version using NNN4NT5 to Vista or higher. A potenital fix would be: inside progwrp.dll, if a NT6 API is found, then disable Thread-Local Storage. I'm not sure if this also affects XP compatibility mode under Win7."

https://github.com/win32ss/supermium/issues/381#issuecomment-2000029174
"That fix would break the Windows 2000 extended kernel. But if there are NT10 functions like SetThreadDescription in OCA then it should be easy, although I am still concerned about these APIs being added in newer extended kernels."
and
"OneCare API is not supported, nor tested with progwrp/Supermium."

**Comment by mina354** [comment]
@jonm58 Ugh, I missed them. Thanks for the response though, glad to know there's a workaround at least.

**Comment by jonm58** [comment]
https://github.com/Alex313031/thorium-win7/releases/tag/M122.0.6261.132
based Supermium,don't have progwrp.dll

**Comment by mina354** [comment]
Thanks, but I like Supermium better.
