### ISSUE TITLE
A few issues

### ISSUE THREAD

**Issue by cesar300** [Skulltrail192/One-Core-API-Binaries#37]
I have three questions:
- After installing this, the Thirteenag fixes for some games refuses to launch or crashes.
- When installing this in a spanish version of XP, after reboot the gui language changes to english. Any chance to update shell32.dll and maybe others from spanish version?
- Any improvements on wined3d? I want to run new games such as need for speed the run or sniper elite V2 without graphics corruption and slowdowns.

Thanks.

**Comment by NEO-SPECTRUMAN** [comment]
>after reboot the gui language changes to english

how to repeat this
![2021-09-13_010844](https://user-images.githubusercontent.com/88002487/133890374-3fd00188-a900-4692-8bd7-022f61e18ed8.png)
?
![2021-09-18_162525](https://user-images.githubusercontent.com/88002487/133890378-31f5a487-4a37-4139-8a02-28bce8805f4b.png)
OCAPI has regional protect :)

**Comment by NEO-SPECTRUMAN** [comment]
LangTypeValue           = 0x09
in 
update_srv2k3.inf 
update_WinXP.inf
in setup temp folder

**Comment by NEO-SPECTRUMAN** [comment]
after change to LangTypeValue=0x041

![2021-09-18_173046](https://user-images.githubusercontent.com/88002487/133892102-1d0bde08-18f0-4bdb-ae0a-fb5a66999fe4.png)
9

there is no OCAPI features works
![2021-09-18_173215](https://user-images.githubusercontent.com/88002487/133892123-4745b398-3875-4808-bf59-d6b1babcc595.png)
![2021-09-18_173233](https://user-images.githubusercontent.com/88002487/133892125-ac3cf819-fd3b-4258-95f8-5729b434c357.png)

**Comment by cesar300** [comment]
Sorry, I can't understand.
All installers except the kernel (stand alone or not) I was succesfully installed on a spanish XP installation.

**Comment by NEO-SPECTRUMAN** [comment]
kernel not installing on russians XP mods
without patching
update_srv2k3.inf
update_WinXP.inf

**Comment by NEO-SPECTRUMAN** [comment]
after install they still not work...

**Comment by NEO-SPECTRUMAN** [comment]
maybe OCAPI need original EN system?

**Comment by cesar300** [comment]
I don't know. I have to test more. I downloaded an original english ISO but I have to install it.

**Comment by Skulltrail192** [comment]
Hello guys, i will create updates for each language or try make a universal (if possible) language installer

**Comment by Lanurence666** [comment]
Please include Chinese. There are lots of users on bilibili expecting for Chinese version.

**Comment by NEO-SPECTRUMAN** [comment]
setup on clear original XP sp3 was successful
no error messages
but OCAPI still not works
launch lock by nt version remais (tryed vista\7\8\10 compatibility mode)
![2021-09-20_231929](https://user-images.githubusercontent.com/88002487/134069552-31256674-d769-4579-a3af-0d21ca275c98.png)

patching pe header also doesn't help
![Uploading 2021-09-20_232314.png…]()

**Comment by Skulltrail192** [comment]
Well, i missed some things with Kernel Installer/Standalone Installer: for prevent is not valid win32 application message, need patch kernel32 to use ntext instedead ntdll, because i made a hack on some nt function and prevent this message. Now i already  fixed it, but, i don't pushed and not released a version. I will change kernelbase and kernel32 and will release new version. It will fix ntdll.dll required funtion too

**Comment by KnIfER** [comment]
@Lanurence666 , Changing `LanguageValue=0x09` to `LanguageValue=0x00` int those two ini files when installing kernel-alone.exe and kernel.exe solved the issue for me.


> ... not valid win32 application

If the application is built using visual studio, under Link->System, the minimal required verison must be set to 5.01 to support XP. Or maybe you can use the VC/.../editbin.exe to modify the exe. I think the XP compat layer is mainly used to solve  the "Cannot locate Entry Point ..." erros.

**Comment by KnIfER** [comment]
I did a few test, it's great!

**SciTE.exe** : run normally, although there's a error message on startup:
```
---------------------------
DirectorExtension: SciTeByLibs.exe - Entry Point Not Found
---------------------------
The procedure entry point RtlIsCriticalSectionLockedByThread could not be located in the dynamic link library ntdll.dll. 
---------------------------
OK   
---------------------------
```

**Notepad++ v8** : No error message, but the save-as dialog is broken and won't show up, newer versions of NPP is using [custom dialog](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9165)  for it's save-as dialogs, which allows putting a custom check button in it.

**Comment by mina354** [comment]
I love the new version 2.0, it's pretty awesome. But, there are some issues. 

- After installing One-Core-API in the right installation order, on the Theme Properties, on Themes and Apperance tab, the sample preview shows up in a different language, and Security Center service stops working. 

- Firefox 53.0 installs and runs before Kernel Update is installed, but after Kernel Update is installed, upon launching it, it says "not a vaild win32 application" (same goes to dxdiag), even though I installed it using the 32 bit installer. 
- Adobe Acrobat Reader DC 2021 doesn't install, even if compatibility mode is set to Windows 7 SP1, it just says "application initalization error". 
- I also tried to install a newer version of [Vivaldi](https://vivaldi.com/download/archive/?platform=win) (1.0 is the last compatible version), for example, 1.1, the installer opens after setting, but it refuses to install Vivaldi because an error comes up and says that the installer is "corrupted", and that I should download the installer again, even though it was already downloaded fully. 

I hope in the next version, you get to solve issues mentioned in this comment, and if you don't understand my issues, I can send some screenshots.

**Comment by mina354** [comment]
Firefox 53 has the titlebar buttons larger (Minimize, Maximize, Close), and uses a different font, instead of the system font:
![image](https://user-images.githubusercontent.com/87821255/136106884-ddb70481-50d3-4932-a5bd-8623b911e93c.png)
While Firefox 52 doesn't:
![image](https://user-images.githubusercontent.com/87821255/136106761-d75d2a91-9767-499f-b332-739b8ab84444.png)
But if i use Windows Classic theme and run Firefox 53, the buttons don't get larger.

Vivaldi 1.1.453.59 doesn't install, because of this error:
![image](https://user-images.githubusercontent.com/87821255/136107550-e523135c-f8ac-4738-b885-a42422015b39.png)
![image](https://user-images.githubusercontent.com/87821255/136107679-4b76aa7c-6fa1-433d-9c97-77ddf02168d2.png)

WinRAR installer (and WinRAR itself) has the graphics (marked in the screenshots below) displayed before One-Core-API is installed, but after One-Core-API is installed, these graphics are gone:
![image](https://user-images.githubusercontent.com/87821255/136108697-b7040db3-c276-4a30-bc32-8ad36d98165a.png)
![image](https://user-images.githubusercontent.com/87821255/136109029-982b1aef-3d66-424f-b2db-abf75aece879.png)

**Comment by Skulltrail192** [comment]
Well, since all problem are fixed or have a workaround, this issue will be closed.
