### ISSUE TITLE
Is the 3D Acceleration works in VirtualBox with XP+OCAPI guest?

### ISSUE THREAD

**Issue by NEO-SPECTRUMAN** [Skulltrail192/One-Core-API-Binaries#53]
Is the 3D Acceleration works in VirtualBox with OCAPI installed?
on 5.2.XX - 6.0.XX versions that still support 3D Acceleration on guest XP
(6.1.0+ dropped 3D Acceleration support on XP guests)

**Comment by vbedesu** [comment]
Use VMware Workstation/Player <=15 for proper hardware acceleration.

**Comment by NEO-SPECTRUMAN** [comment]
i tryed several versions
VirtualBox-4.2.0-80737 works ~stable with dx8 dx9
VirtualBox-4.2.0-80737+ not works

**Comment by Skulltrail192** [comment]
Well, Virtualbox has OpenGL Accelaration? You must install D3D Runtime Update AFTER VirtualBox tools installation, because if you install VirtualBox tools after D3d Runtime, it will be overwrite d3d files (if you selected 3d acceleration on Virtual Box installation options) and you were lost 3d acceleration.

**Comment by Skulltrail192** [comment]
Confirmed, virtualBox removed 3d accelaration, not only for Windows XP, but, every Windows system. So, this issue will be closed, because nothing to be done.

**Comment by ajalberd** [comment]
Even in VMWare player, the 3d acceleration is abysmal for default XP. Can this program help with any of that?
